Improve documentation for usage
GenrikhFetischev/async_uws pull request #4
Opened 2023-11-25 19:32 UTC by YassinEldeeb

2023-11-27 19:35 UTC, GenrikhFetischev requested changes
Overall it's a great contribution, thank you! 🙏
Could you please update section for Windows users according to my comment?

2023-11-27 19:35 UTC, GenrikhFetischev commented on README.md
> +### Windows Users
Actually, right now that library doesn't support Windows at all,  because of [libuwebsockets-sys crate build script](https://github.com/GenrikhFetischev/libuwebsockets-sys/blob/main/build.rs#L13). (which is dependency in uwebsockets_rs thus in async_uws). So, with that update I'll don't hesitate to merge this PR.

2023-11-28 00:55 UTC, YassinEldeeb commented on README.md
> +### Windows Users
Updated!

2023-11-28 00:56 UTC, YassinEldeeb commented on README.md
> +For Windows users, the setup process might involve additional steps such as using `vcpkg` or another package manager to install `libuv` and setting up the environment for `MSVC` or `MinGW`.
```suggestion
Unfortunately this library doesn't currently support Windows, but please don't hesitate sending a PR for Windows support at [libuwebsockets-sys crate build script](https://github.com/GenrikhFetischev/libuwebsockets-sys/blob/main/build.rs#L13)
```

2023-11-28 08:49 UTC, GenrikhFetischev approved these changes

2023-11-28 08:49 UTC, merged